name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-amd64-binary
          path: ./build/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: darwin-amd64-binary
          path: ./build/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-amd64-binary
          path: ./build/windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.workflow_run.head_commit.id }}
          release_name: Release ${{ github.event.workflow_run.head_commit.id }}
          body: |
            Release notes for ${{ github.event.workflow_run.head_commit.id }}.
          draft: false
          prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/linux/myapp-linux-amd64
          asset_name: myapp-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/macos/myapp-darwin-amd64
          asset_name: myapp-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/windows/myapp-windows-amd64
          asset_name: myapp-windows-amd64.exe
          asset_content_type: application/octet-stream